id: P001859
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD181196
  title: རྫོགས་ཆེན་མན་ངག་གི་སྐོར་རྡོ་རྗེ་གནད་བརྡེག
  author: ''
  volumes:
    27e0edc5bf5741ba8111ede4b9851f4c:
      image_group_id: I1KG16381
      title: ''
      volume_number: 1
      total_pages: 79
