id: I56BF403F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T16:34:40+00:00'
last_modified: '2022-06-07T15:24:44.110690+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181196
  title: རྫོགས་ཆེན་མན་ངག་གི་སྐོར་རྡོ་རྗེ་གནད་བརྡེག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    17D5:
      image_group_id: I1KG16381
      title: ''
      total_pages: 79
      order: 1
      base_file: 17D5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
